CDN Upload of Profile images
NIAEFEUP/Website-NIAEFEUP pull request #199
Opened 2020-09-26 14:43 UTC by andrefmrocha

In order to solve several issues regarding the storage of photos locally, a strategy using Cloudinary's CDN was created, in order to have a better method of storage of photos. 
This strategy does not completely substitute the local storage, since it uses the presence of Cloudinary CDN environment variable to detect if it should use local storage or CDN storage.

2020-09-26 15:25 UTC, GambuzX approved these changes, later dismissed
Looks good, just left 2 questions.
Also, when displaying the profile picture, is it the same to fetch the picture from a remote url or a local path? Nothing has to be changed on that part?

2020-09-26 15:25 UTC, GambuzX commented on src/routes/api/profilephoto.js
> +			console.log(item);
Is this log required?

2020-09-26 15:25 UTC, GambuzX commented on src/routes/api/profilephoto.js
> +					item.attributes1 = img.public_id;
Why is item.attributes1 only set if using cloudinary? What does it do?

2020-09-26 15:26 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +					item.attributes1 = img.public_id;
I use this attribute as a tag to know which ID to delete from the CDN on an image update

2020-09-26 15:27 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +			console.log(item);
Totally missed it, thanks!

2020-09-26 15:28 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +					item.attributes1 = img.public_id;
The goal of attributes1 is to be use as any sort of tag you wish to use.

2020-09-26 15:33 UTC, GambuzX approved these changes, later dismissed

2020-09-26 18:52 UTC, imnotteixeira requested changes
Good initiative! Just requesting some changes to fix problems that could arise.

2020-09-26 18:52 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +const isProd = process.env.CLOUDINARY_URL;
The naming here is misleading: It doesn't really tell if this is a prod environment.

2020-09-26 18:52 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +const isProd = process.env.CLOUDINARY_URL;
I'd replace it with `CLOUDINARY_API_URL`

2020-09-26 18:52 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +			`data:image/png;base64,${data.toString("base64")}`,
Is it certain that the image will be a png?

2020-09-26 18:52 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +					item.attributes1 = img.public_id;
If you use this only to store the cloudinary image id, then rename it to cloudinary_id or something similar. `attributes1` is really vague.

2020-09-26 18:52 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +				cloudinary.uploader.destroy(model.attributes1);
When changing attributes1 naming, do not forget to update here. If only this was typescript....

2020-09-26 18:52 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +const createPhoto = function (req, data) {
Where does the `data` param come from?

2020-09-26 18:52 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +		const update = async () => {
By making createPhoto  an async function like this:
```js
const createPhoto = async (req, data) => {}
```

you can take yout the return new Promise part, and the update() function just becomes the outer function body, since you will be in the async world already. If you need to reject the promise, simply throw the error.

In the current version, the update function being async is not being "respected", since you don't wait for the result when calling it. The suggestion above fixes that as well.

2020-09-26 18:56 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +					item.attributes1 = img.public_id;
This would require a change to the model, this is why it wasn't done. Are you sure that is the best course of action?

2020-09-26 18:58 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +const createPhoto = function (req, data) {
`data` is an image buffer created by SharpJS [here](https://github.com/NIAEFEUP/Website-NIAEFEUP/blob/891ad09a918d44fc72d9e0a6ae90c8c893afc701/src/routes/api/profilephoto.js#L129).

2020-09-26 19:01 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +		const update = async () => {
I'm not sure that's the case since at the end there's [a call to a save method](https://github.com/NIAEFEUP/Website-NIAEFEUP/blob/891ad09a918d44fc72d9e0a6ae90c8c893afc701/src/routes/api/profilephoto.js#L93) which ends in a callback which doesn't seem to have a promise returning counterpart

2020-09-26 19:02 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +			`data:image/png;base64,${data.toString("base64")}`,
The image is indeed created by us through sharp so the type is expected. What's curious is that technically I did use png here whilst converting the images to jpeg, I wonder how that has worked either way

2020-09-26 20:37 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +				cloudinary.uploader.destroy(model.attributes1);
In this case, store the model.attributes1 in a more specific variable like cloudinary_id to use here and make it clearer for future devs

2020-09-26 20:42 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +			`data:image/png;base64,${data.toString("base64")}`,
Oh.. I see, you're right. In any case, I think this is proof that the code is not readable enough and code be improved and simplified in the mentioned way

2020-09-26 20:43 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +					item.attributes1 = img.public_id;
ugh... ok. Check the suggestion above then, for the field usage.

2020-09-26 20:45 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +		const update = async () => {
Oh.. I see, you're right. In any case, I think this is proof that the code is not readable enough and code be improved and simplified in the mentioned way

2020-09-26 20:53 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +		const update = async () => {
So are you suggesting that I return `item` no matter what and just throw the error in the callback if anything goes wrong? Won't the promise be already resolved by and the error throw ignored? I'm not sure I follow how do you wish to approach this, since I do need to check on that callback. The only reason instantiating a promise myself was due to that callback that I need to check on

2020-09-27 09:03 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +		const update = async () => {
I was going for something like this:

```js
const createPhoto = async function(req, data) {
    const item = new FileData.model();
    const userId = req.user._id;

    item.fileType = item.file.mimetype;
    item.createdTimeStamp = new Date();
    item.name = userId;

    if (isProd) {
        const img = await cdnUpload(data);
        item.url = img.secure_url;
        item.attributes1 = img.public_id;
    } else {
        await writeFile(req.files.file_upload.path, data);
        const new_path = `/uploads/members/${item.file.filename}`;
        item.url = new_path;
    }

    return item.save();
}
```

No need for try catch, since they were just throwing the error anyway, it will have the same behavior.
Regarding the save() call, it is async https://mongoosejs.com/docs/api.html#model_Model-save and checking the error to reject the promise is the same as letting it throw naturally here.

2020-09-27 09:04 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +		const update = async () => {
Also, this reduces the function size in 10+ lines

2020-09-27 15:52 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +const isProd = process.env.CLOUDINARY_URL;
Done!

2020-09-27 15:52 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +				cloudinary.uploader.destroy(model.attributes1);
Done!

2020-09-27 15:53 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +		const update = async () => {
Ah I was not aware that the models representation used in KeystoneJS was mongoose's, that;s why I thought there wasn't a promise returning save method. Thanks!

2020-09-27 15:54 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +			`data:image/png;base64,${data.toString("base64")}`,
Even there's no change in behavior, I changed this to be semantically correct.

2020-09-27 16:45 UTC, imnotteixeira requested changes

2020-09-27 16:45 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +};
This can be simplified into:
```js
const promisify = require("util").promisify;
....
const cdnUpload = async (data) => {
    const upload = promisify(coudinary.uploader.upload);
    return await upload(`data:image/jpeg;base64,${data.toString("base64")}`)
};
```

2020-09-27 16:47 UTC, imnotteixeira commented on src/routes/api/profilephoto.js
> +};
Actually you don't even need the async/await, since the returned value is a promise. So you can even define the upload function at the top of the file (as it was an import) and then in this function you just 

```
const cdnUpload = (data) => return upload(`data:....`)
```

2020-09-27 16:52 UTC, andrefmrocha commented on src/routes/api/profilephoto.js
> +};
Was not aware of the `promisify` utility function, thanks!

2020-09-27 16:58 UTC, imnotteixeira approved these changes
Looks ok now, please make sure the code actually works after these changes before merging

2020-09-27 17:02 UTC, andrefmrocha commented
> Looks ok now, please make sure the code actually works after these changes before merging

Yeah it has been tested. We will also finally deploy a staging environment for the website after this!

2020-09-28 15:21 UTC, GambuzX approved these changes
Looks good

2020-09-28 15:22 UTC, merged